[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"
  VITE_CLOUDINARY_CLOUD_NAME = "dhxetyrkb"
  VITE_CLOUDINARY_API_KEY = "878769551721862"
  CLOUDINARY_CLOUD_NAME = "dhxetyrkb"
  CLOUDINARY_API_KEY = "878769551721862"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
