[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"
  NODE_ENV = "production"
  VITE_API_URL = "/.netlify/functions"
  VITE_CLOUDINARY_CLOUD_NAME = "dhxetyrkb"
  VITE_CLOUDINARY_API_KEY = "878769551721862"
  CLOUDINARY_CLOUD_NAME = "dhxetyrkb"
  CLOUDINARY_API_KEY = "878769551721862"

[functions]
  external_node_modules = ["express", "@neondatabase/serverless"]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
