[build]
  publish = "dist"
  command = "VITE_NODE_ENV=production NODE_ENV=production CI=false npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"
  VITE_NODE_ENV = "production"
  NODE_ENV = "production"
  VITE_CLOUDINARY_CLOUD_NAME = "dhxetyrkb"
  VITE_CLOUDINARY_API_KEY = "878769551721862"
  CLOUDINARY_CLOUD_NAME = "dhxetyrkb"
  CLOUDINARY_API_KEY = "878769551721862"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
